//! The icons of the GUI: Lucide glyphs (ISC) in the font gui/assets/fonts/lucide.ttf.
//! Generated by gui/assets/fonts/build.py: change the list there.

/// An icon of the embedded font; `.glyph()` is its character.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Icon {
    ChevronDown,
    ChevronRight,
    ChevronUp,
    Restart,
    Reset,
    Reload,
    Rolling,
    SafeReload,
    Hard,
    Play,
    Stop,
    Power,
    Plus,
    Minus,
    Settings,
    Edit,
    Copy,
    Check,
    Close,
    Search,
    Server,
    Globe,
    Plug,
    Unplug,
    Laptop,
    Activity,
    Logs,
    History,
    Cpu,
    Memory,
    Clock,
    Alert,
    AlertCircle,
    CheckCircle,
    Shield,
    Terminal,
    Link,
    ExternalLink,
    User,
    Network,
    Ellipsis,
    Pause,
    Info,
    Loader,
    Wifi,
    WifiOff,
    Boxes,
    Workers,
    Folder,
    Timer,
}

impl Icon {
    pub const fn glyph(self) -> char {
        match self {
            Icon::ChevronDown => '\u{e06d}',  // chevron-down
            Icon::ChevronRight => '\u{e06f}', // chevron-right
            Icon::ChevronUp => '\u{e070}',    // chevron-up
            Icon::Restart => '\u{e149}',      // rotate-cw
            Icon::Reset => '\u{e148}',        // rotate-ccw
            Icon::Reload => '\u{e145}',       // refresh-cw
            Icon::Rolling => '\u{e529}',      // layers
            Icon::SafeReload => '\u{e1ff}',   // shield-check
            Icon::Hard => '\u{e1b4}',         // zap
            Icon::Play => '\u{e13c}',         // play
            Icon::Stop => '\u{e167}',         // square
            Icon::Power => '\u{e140}',        // power
            Icon::Plus => '\u{e13d}',         // plus
            Icon::Minus => '\u{e11c}',        // minus
            Icon::Settings => '\u{e154}',     // settings
            Icon::Edit => '\u{e31f}',         // file-pen
            Icon::Copy => '\u{e09e}',         // copy
            Icon::Check => '\u{e06c}',        // check
            Icon::Close => '\u{e1b2}',        // x
            Icon::Search => '\u{e151}',       // search
            Icon::Server => '\u{e153}',       // server
            Icon::Globe => '\u{e0e8}',        // globe
            Icon::Plug => '\u{e37f}',         // plug
            Icon::Unplug => '\u{e45d}',       // unplug
            Icon::Laptop => '\u{e1cd}',       // laptop
            Icon::Activity => '\u{e038}',     // activity
            Icon::Logs => '\u{e45f}',         // scroll-text
            Icon::History => '\u{e2a5}',      // chart-line
            Icon::Cpu => '\u{e0a9}',          // cpu
            Icon::Memory => '\u{e445}',       // memory-stick
            Icon::Clock => '\u{e087}',        // clock
            Icon::Alert => '\u{e193}',        // triangle-alert
            Icon::AlertCircle => '\u{e077}',  // circle-alert
            Icon::CheckCircle => '\u{e226}',  // circle-check
            Icon::Shield => '\u{e158}',       // shield
            Icon::Terminal => '\u{e181}',     // terminal
            Icon::Link => '\u{e102}',         // link
            Icon::ExternalLink => '\u{e0b9}', // external-link
            Icon::User => '\u{e19f}',         // user
            Icon::Network => '\u{e125}',      // network
            Icon::Ellipsis => '\u{e0b6}',     // ellipsis
            Icon::Pause => '\u{e12e}',        // pause
            Icon::Info => '\u{e0f9}',         // info
            Icon::Loader => '\u{e109}',       // loader
            Icon::Wifi => '\u{e1ae}',         // wifi
            Icon::WifiOff => '\u{e1af}',      // wifi-off
            Icon::Boxes => '\u{e2d0}',        // boxes
            Icon::Workers => '\u{e529}',      // layers
            Icon::Folder => '\u{e0d7}',       // folder
            Icon::Timer => '\u{e1e0}',        // timer
        }
    }
}
