//! The icons of the GUI: Lucide glyphs (ISC) in the font gui/assets/fonts/lucide.ttf.
//! Generated by gui/assets/fonts/build.py: change the list there.

/// An icon of the embedded font; `.glyph()` is its character.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Icon {
    ChevronDown,
    ChevronRight,
    ChevronUp,
    Restart,
    Reset,
    Reload,
    Rolling,
    SafeReload,
    Hard,
    Play,
    Stop,
    Power,
    Plus,
    Minus,
    Settings,
    Edit,
    Copy,
    Check,
    Close,
    Search,
    Server,
    Globe,
    Plug,
    Unplug,
    Laptop,
    Activity,
    Logs,
    History,
    Cpu,
    Memory,
    Clock,
    Alert,
    AlertCircle,
    CheckCircle,
    Shield,
    Terminal,
    Link,
    ExternalLink,
    User,
    Network,
    Ellipsis,
    Pause,
    Info,
    Loader,
    Wifi,
    WifiOff,
    Boxes,
    Workers,
    Folder,
    Timer,
    Sun,
    Moon,
    SunMoon,
    Palette,
    Monitor,
    Save,
    Trash,
    Maximize,
    Minimize,
}

impl Icon {
    /// Every icon, in the order of the list in build.py (a test draws each).
    pub const ALL: [Icon; 59] = [
        Icon::ChevronDown,
        Icon::ChevronRight,
        Icon::ChevronUp,
        Icon::Restart,
        Icon::Reset,
        Icon::Reload,
        Icon::Rolling,
        Icon::SafeReload,
        Icon::Hard,
        Icon::Play,
        Icon::Stop,
        Icon::Power,
        Icon::Plus,
        Icon::Minus,
        Icon::Settings,
        Icon::Edit,
        Icon::Copy,
        Icon::Check,
        Icon::Close,
        Icon::Search,
        Icon::Server,
        Icon::Globe,
        Icon::Plug,
        Icon::Unplug,
        Icon::Laptop,
        Icon::Activity,
        Icon::Logs,
        Icon::History,
        Icon::Cpu,
        Icon::Memory,
        Icon::Clock,
        Icon::Alert,
        Icon::AlertCircle,
        Icon::CheckCircle,
        Icon::Shield,
        Icon::Terminal,
        Icon::Link,
        Icon::ExternalLink,
        Icon::User,
        Icon::Network,
        Icon::Ellipsis,
        Icon::Pause,
        Icon::Info,
        Icon::Loader,
        Icon::Wifi,
        Icon::WifiOff,
        Icon::Boxes,
        Icon::Workers,
        Icon::Folder,
        Icon::Timer,
        Icon::Sun,
        Icon::Moon,
        Icon::SunMoon,
        Icon::Palette,
        Icon::Monitor,
        Icon::Save,
        Icon::Trash,
        Icon::Maximize,
        Icon::Minimize,
    ];

    pub const fn glyph(self) -> char {
        match self {
            Icon::ChevronDown => '\u{e06d}',  // chevron-down
            Icon::ChevronRight => '\u{e06f}', // chevron-right
            Icon::ChevronUp => '\u{e070}',    // chevron-up
            Icon::Restart => '\u{e149}',      // rotate-cw
            Icon::Reset => '\u{e148}',        // rotate-ccw
            Icon::Reload => '\u{e145}',       // refresh-cw
            Icon::Rolling => '\u{e529}',      // layers
            Icon::SafeReload => '\u{e1ff}',   // shield-check
            Icon::Hard => '\u{e1b4}',         // zap
            Icon::Play => '\u{e13c}',         // play
            Icon::Stop => '\u{e167}',         // square
            Icon::Power => '\u{e140}',        // power
            Icon::Plus => '\u{e13d}',         // plus
            Icon::Minus => '\u{e11c}',        // minus
            Icon::Settings => '\u{e154}',     // settings
            Icon::Edit => '\u{e31f}',         // file-pen
            Icon::Copy => '\u{e09e}',         // copy
            Icon::Check => '\u{e06c}',        // check
            Icon::Close => '\u{e1b2}',        // x
            Icon::Search => '\u{e151}',       // search
            Icon::Server => '\u{e153}',       // server
            Icon::Globe => '\u{e0e8}',        // globe
            Icon::Plug => '\u{e37f}',         // plug
            Icon::Unplug => '\u{e45d}',       // unplug
            Icon::Laptop => '\u{e1cd}',       // laptop
            Icon::Activity => '\u{e038}',     // activity
            Icon::Logs => '\u{e45f}',         // scroll-text
            Icon::History => '\u{e2a5}',      // chart-line
            Icon::Cpu => '\u{e0a9}',          // cpu
            Icon::Memory => '\u{e445}',       // memory-stick
            Icon::Clock => '\u{e087}',        // clock
            Icon::Alert => '\u{e193}',        // triangle-alert
            Icon::AlertCircle => '\u{e077}',  // circle-alert
            Icon::CheckCircle => '\u{e226}',  // circle-check
            Icon::Shield => '\u{e158}',       // shield
            Icon::Terminal => '\u{e181}',     // terminal
            Icon::Link => '\u{e102}',         // link
            Icon::ExternalLink => '\u{e0b9}', // external-link
            Icon::User => '\u{e19f}',         // user
            Icon::Network => '\u{e125}',      // network
            Icon::Ellipsis => '\u{e0b6}',     // ellipsis
            Icon::Pause => '\u{e12e}',        // pause
            Icon::Info => '\u{e0f9}',         // info
            Icon::Loader => '\u{e109}',       // loader
            Icon::Wifi => '\u{e1ae}',         // wifi
            Icon::WifiOff => '\u{e1af}',      // wifi-off
            Icon::Boxes => '\u{e2d0}',        // boxes
            Icon::Workers => '\u{e529}',      // layers
            Icon::Folder => '\u{e0d7}',       // folder
            Icon::Timer => '\u{e1e0}',        // timer
            Icon::Sun => '\u{e178}',          // sun
            Icon::Moon => '\u{e11e}',         // moon
            Icon::SunMoon => '\u{e2b2}',      // sun-moon
            Icon::Palette => '\u{e1dd}',      // palette
            Icon::Monitor => '\u{e11d}',      // monitor
            Icon::Save => '\u{e14d}',         // save
            Icon::Trash => '\u{e18e}',        // trash-2
            Icon::Maximize => '\u{e113}',     // maximize-2
            Icon::Minimize => '\u{e11b}',     // minimize-2
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `ALL` is the enum, variant for variant and in order: a test draws each icon of `ALL`, so a
    /// variant left out of it would never be checked against the font.
    #[test]
    fn all_lists_every_variant_of_the_enum_once() {
        let source = include_str!("icons.rs");
        let body = source.split("pub enum Icon {").nth(1).and_then(|s| s.split("\n}").next()).expect("the enum");
        let declared: Vec<&str> =
            body.lines().map(|l| l.trim().trim_end_matches(',')).filter(|l| !l.is_empty()).collect();
        let listed: Vec<String> = Icon::ALL.iter().map(|i| format!("{i:?}")).collect();
        assert_eq!(listed, declared);
    }
}
